### PR TITLE
Adding board definition for admpa100_2ms, version 1.0

### PR DESCRIPTION
**Pull request by twhitlock**

### CODE REVIEW

**Comment by bmansouramd** [comment]
ok to test

**Comment by twhitlock** [comment]
Should I also have a pull request to the master branch, so that future Vivado versions, e.g. 2023.1, will automatically have a board file that is the same as the 2022.2 branch?

**Comment by Abhinav2016** [comment]
ok to test

**Review by vsrunga — APPROVED** [review]

**Comment by vsrunga** [comment]
ok to test

**Pull request merged**
