### PR TITLE
Deleting au50 github board files

### PR DESCRIPTION
**Pull request by ghost**
Removing au50 github board files. The source board files should be the one with the au50 XSA in TA.

### CODE REVIEW

**Comment by abalasa** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Comment by abalasa** [comment]
retest this please

**Review by AVXilinx — APPROVED** [review]

**Comment by AVXilinx** [comment]
Closing the pull request. Developer to create a new pull request after updating their repo to avoid conflict.

**Pull request closed without merging**
