### PR TITLE
2019.2

### PR DESCRIPTION
**Pull request by JH515**
Please update to 19.2 and newer

### CODE REVIEW

**Comment by Premduth** [comment]
@vsrunga  can you see why there is a branch conflict here?

**Comment by vsrunga** [comment]
> @vsrunga can you see why there is a branch conflict here?

Hi Duth,

From what I see, user JH515 is trying to push some changes to vivado_2019.2.json but the store has a more recent version and hence flags the conflict. I think user need to fork the latest copy and then do the changes or leave catalog updates to Store Admins or pipeline.

**Review by Premduth — CHANGES_REQUESTED** [review]
The branch has been updated and thus this change is causing merge conflicts. Please ensure that your version is rebased to the latest in the repo and resubmit this request.

**Comment by JH515** [comment]
Hi,
you can reverse my  19.2 pull request from 19.2.1 into 19.2.  This was done accidentally as I had extended writing rights in your git. I wrote this to Adithya, and your support email "xilinx_store_support@xilinx.com" at 2020-08-07. After you confirmed that I had the wrong rights.
br
John

**Comment by JH515** [comment]
Hi,
you can reverse my  19.2 pull request from 19.2.1 into 19.2.  This was done accidentally as I had extended writing rights in your git. I wrote this to Adithya, and your support email "xilinx_store_support@xilinx.com" at 2020-08-07. After you confirmed that I had the wrong rights.
br
John

**Comment by JH515** [comment]
Hi,
you can reverse my  19.2 pull request from 19.2.1 into 19.2.  This was done accidentally as I had extended writing rights in your git. I wrote this to Adithya, and your support email "xilinx_store_support@xilinx.com" at 2020-08-07. After you confirmed that I had the wrong rights.
br
John

**Comment by Premduth** [comment]
Ah yes! Sorry about that.. This was a very old one that was just sitting around. We closed the PR, so now you can rebase and do a new PR as needed.

**Pull request closed without merging**
