### PR TITLE
Added pynq_z2 board files

### PR DESCRIPTION
**Pull request by megastefan22**
Board Files were taken from [https://www.tulembedded.com/FPGA/ProductsPYNQ-Z2.html](https://www.tulembedded.com/FPGA/ProductsPYNQ-Z2.html)

### CODE REVIEW

**Comment by dosarudaniel** [comment]
It would be great to have the PYNQ-Z2 board file in the XilinxBoardStore repository

**Comment by AVXilinx** [comment]
ok to test

**Comment by rkunwar-xilinx** [comment]
This pull request is missing the required xitem.json file.
Please follow https://github.com/Xilinx/XilinxBoardStore/wiki/Adding-a-New-XItem-to-the-Repository to add new board files to the repository.

**Comment by Premduth** [comment]
Please fix the issue identified by @rkunwar-xilinx

**Pull request closed without merging**
