### PR TITLE
Added Board Files

### PR DESCRIPTION
**Pull request by iWave-1234**
Hii,

Added 11eg, 19eg board files in this pull request. Please review the same and share you comments

### CODE REVIEW

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by iWave-1234** [comment]
Hi
Why it shows merging is blocked  ?

**Comment by iWave-1234** [comment]
Hi,
Can any one please check on  the previous question.

**Comment by ADubeyAMD** [comment]
@iWave-1234, Our pipeline is flagging a file which has been added and removed in various commits. Can you please create a new branch and include only the boards that needs to be added (created) and raise a new Pull request.

**Comment by ADubeyAMD** [comment]
@iWave-1234 please check the comment above and do the needful, thank you

**Pull request closed without merging**
