### PR TITLE
Trenz Board Files

### PR DESCRIPTION
**Pull request by JH515**
-add new board file
-rename some board files
-add new variant names to existing board files

### CODE REVIEW

**Comment by Premduth** [comment]
ok to test

**Comment by JH515** [comment]
Hi,
do you know what's failed?
I've done similar pull request on Monday for 2021.2 which passed (https://github.com/Xilinx/XilinxBoardStore/pull/500).
I've compared files, they are the same(except the category  entry in some of the json file of some board files (changed from "uncategorized" to "Zynq UltraScale+ MPSoC/Module" which  I also use it on other board files))
br
John

**Comment by vsrunga** [comment]
Error is flagged at much early stage during git fetch. 
@Xilinx/sabarinath , @rkunwar-xilinx

**Comment by Premduth** [comment]
please retest

**Comment by Premduth** [comment]
Ok to test

**Comment by JH515** [comment]
Thanks for the merge. 
br
John

**Pull request merged**
