### PR TITLE
Adding iwave board files

### PR DESCRIPTION
**Pull request by iWave-1234**

### CODE REVIEW

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
retest this please

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by sabarinaxil** [comment]
retest this please

**Comment by iWave-1234** [comment]
we are already validated it from our side .

**Comment by ADubeyAMD** [comment]
@iWave-1234, We are facing some problems with merging the PR. We have identified some issues that has to be discussed. Can you please contact us on the following email ID: subbuh@amd.com , to discuss further, thank you

**Comment by ADubeyAMD** [comment]
@iWave-1234, please reply to the message above or please share an email ID where you can be contacted. Thanks

**Comment by iWave-1234** [comment]
Please contact to this mail ID ***@***.***

Regards
Madhu O

**Comment by ADubeyAMD** [comment]
@iWave-1234, Hi I am unable to access the email. Looks like Github has hidden the email ID, I see only asterisks. Can you please email directly on subbuh@amd.com to resolve this issue on priority, thank you!

**Comment by iWave-1234** [comment]
@ADubeyAMDI have already sent a mail to subbuh@amd.com from madhu.oladi@iwavesystems.com on 18th April 2023. But I haven't get any response. I have attached the screenshot of my mail id also.
image

**Pull request closed without merging**
