### PR TITLE
Adding board definition for admpa101_2ms, version 1.1

### PR DESCRIPTION
**Pull request by twhitlock**

### CODE REVIEW

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
OK to test

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
@twhitlock Why are these PR merges for 2021.1 branch. Is this intentional ? Please confirm

**Comment by twhitlock** [comment]
@ADubeyAMD

Yes, this is intentional. From our point of view, 2021.1 is when XCVC1902 / XCVM1802 support in Xilinx tools became reasonably stable and so 2021.1 to 2022.2 is the tool range that we officially support in most of our examples etc. for our ADM-PA100/101 products. We still encourage customers to use the latest tool version for a new project, though.

I believe Xilinx officially support the latest two tool versions (e.g. 2022.2 and 2022.1 as I write this) but some customers, especially corporate ones, are often reluctant to immediately upgrade whenever a new Vivado version is released. For the aforementioned products we decided that 2021.1 to 2022.2 was a reasonable tool version range for us to support because we had figured out most of the issues and solutions.

Is this resulting in too much work for Xilinx merging pull requests?

**Comment by ADubeyAMD** [comment]
Hi @twhitlock , thank you for confirmation. It's not an issue as we can merge the pull requests in released branches. We just wanted to rule out any possibility of unintended merges. Thank you

**Pull request merged**
