### PR TITLE
master OpalKelly: Add New BFs. Update Existing BF

### PR DESCRIPTION
**Pull request by KristofMcLovin**
- Add all XEM73xx and XEM83xx board files
- Update URL to product page on BRK1900 and SZG board files
- Release v1.2 XEM8320-AU25P board file
- Release v1.1 SZG-ENET1G board file

### CODE REVIEW

**Comment by Premduth** [comment]
Ok to test

**Comment by KristofMcLovin** [comment]
@Premduth Any information on why the check has failed? Thanks

**Comment by Premduth** [comment]
@KristofMcLovin having someone look into this. Seems like it is something on our side. @kunwar-rahul  can you take a look please? It seems to have failed in the catalog update

**Comment by Premduth** [comment]
Ok to test

**Comment by KristofMcLovin** [comment]
@Premduth @kunwar-rahul Thanks. Let me know if anything is needed on my end. I can manually update the catalog if necessary.

**Comment by sabarinaxil** [comment]
retest this please

**Comment by KristofMcLovin** [comment]
@Premduth @kunwar-rahul @sabarinaxil Any update/resolution on this?

**Comment by Premduth** [comment]
Opened an issue request: https://github.com/Xilinx/XilinxBoardStore/issues/581

**Comment by sabarinaxil** [comment]
Hi @KristofMcLovin ,
Can you check if the file "boards/OpalKelly/XEM7320-A200/1.0/board.xml " is well formed, i believe file has syntax issues.

Issue is at line 377 "<connection" is not closed.

@Premduth

**Comment by KristofMcLovin** [comment]
@sabarinaxil Thanks! Resolved at commit 5a4d7144f46cc2166c719e1e5786848068afc52e

**Pull request merged**
