### PR TITLE
Update for Trenz Electronic Board Files

### PR DESCRIPTION
**Pull request by JH515**
- update all xitem.json with 2020.1 python script
- add 113 new board file
- modify 64 existing board files
- delete 4 obsolete board files

### CODE REVIEW

**Comment by AVXilinx** [comment]
ok to test

**Comment by jaipalr-xilinx** [comment]
This pull request failed in validation. We observed that there are multiple entries for xitem: te0741_160_2c v2.0.
boards/Trenz_Electronic/TE0741_160_2C/2.0/xitem.json
boards/Trenz_Electronic/TE0741_160_3E/2.0/xitem.json

Above two xitem.json files have same xitem name "te0741_160_2c".  Please fix this.

**Comment by Premduth** [comment]
ok to test

**Review by jaipalr-xilinx — APPROVED** [review]
Passed in validation. Good to merge.

**Comment by jaipalr-xilinx** [comment]
Reverted this change as it is causing xhub::refresh_catalog to fail. 
ERROR: [Common 17-1475] Error reading json file 'boards/Trenz_Electronic/TE0725LP/1.0/xitem.json'.

**Comment by JH515** [comment]
Hi,
can you explain me why you has reverse my pull request?
boards/Trenz_Electronic/TE0725LP was one of 4  obsolete board part files which should be deleted from the catalog.
br
John

**Comment by JH515** [comment]
Hi,
sorry,it looks my summery procedure has count TE0725LP twice. 

So there was 3 board parts which was deleted:
\Trenz_Electronic\TE0725LP\1.0
\Trenz_Electronic\TE0803_4EG_1I\5.0
\Trenz_Electronic\TE0803_4EG_1I\6.0

Git has defined them as renaming to new board files in the log (I don't know why), but the result is the same this board files does not longer exists.

I think this files was still defined in the catalog file which cause this last error. 

So please let me know what I must do to merge all Trenz board files (including add, modified and remove board files) with your git?

br
John

**Comment by jaipalr-xilinx** [comment]
Hi John,

We are working on it to merge your pull request with corresponding catalog file. Hopefully we should be able to merge your pull request today if there are no further validation errors. We will let you know if we need anything more. 

Regards,
Jaipal

**Comment by JH515** [comment]
Hi Jaipal,

thank you very much for the merging, everything works fine now. :-)

br
John

**Pull request merged**
