### PR TITLE
vck190 and vmk180 update to master

### PR DESCRIPTION
**Pull request by shivakemidi**

### CODE REVIEW

**Review by vsrunga — APPROVED** [review]

**Comment by vsrunga** [comment]
ok to test

**Comment by sabarinaxil** [comment]
retest this please

**Comment by vsrunga** [comment]
Same changes have passed pipelining tests in 2020.2 branch, so looks something is broken in Master ?

**Comment by sabarinaxil** [comment]
retest this please

**Comment by sabarinaxil** [comment]
retest this please

**Comment by sabarinaxil** [comment]
retest this please

**Pull request merged**
