### PR TITLE
Initial Release K24 Development Kit for Tria

### PR DESCRIPTION
**Pull request by dsaveski**
This release contains the BDF for the K24 SOM and K24 IO Carrier Card that makes up the K24 Development Kit.

### CODE REVIEW

**Comment by dsaveski** [comment]
I am trying to release initial BDFs of two boards to the Avnet sub-group. I'm not sure if I performed that correctly. This code was developed for 2024.1 which is the targeted branch.

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
@dsaveski the error in the Github pipeline suggests that this PR was closed for the first time with getting approved and then reopened, thus the pipeline is unable to detect unique files. Can you please close this Pull request and raise a new Request. Please do not close the PR until it is approved atleast one to trigger the pipeline. Thanks

**Comment by dsaveski** [comment]
Closing pull request per direction from ADubeyAMD

**Pull request closed without merging**
