### PR TITLE
2022.2

### PR DESCRIPTION
**Pull request by iWave-1234**

### CODE REVIEW

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
@iWave-1234, there is a branch conflict in this Pull request, can you please resolve the conflict and Raise Pull Request again, thank you

**Comment by iWave-1234** [comment]
Hi
 Last time i resolved it and upload the file in separate Branch "Iwave_latest_merge" the same file only i used here also.

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
@iWave-1234 , there is no problem with the files, the problem is due to git conflict. Can you please perform the following steps : 
image

**Comment by ADubeyAMD** [comment]
@iWave-1234 can you please check the comment above and do the needful. thanks

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
@iWave-1234 looks like the conflict has still not been resolved at your end, please do the needful per the messages sent earlier

**Comment by iWave-1234** [comment]
@ADubeyAMD please may i know that is these board file are available in Vivado GUI 2022.2?

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
@iWave-1234, no they won't be available. As i mentioned in previous comments multiple times, branch conflict has to be resolved at your end for the new files to be merged. This is a limitation from Github for version control. Please resolve the conflict mentioned earlier and raise a Pull request again and It will be available after test is successful

**Comment by iWave-1234** [comment]
@ADubeyAMD,  Can you please share the conflict log and  kindly provide the procedure for resolving the issue. So that will help us to resolve the issue from our side

**Comment by ADubeyAMD** [comment]
@iWave-1234 , please find the steps below.
image

**Comment by iWave-1234** [comment]
Please close the pull request.

**Pull request closed without merging**
