### PR TITLE
Revert "Deleting Digilent Boards which has XML format issues"

### PR DESCRIPTION
**Pull request by sabarinaxil**
This reverts commit c72fe5ef47a3304bd0fd619dde375ba98cba561a. Testing for getting latest log on xml issues

### CODE REVIEW

**Comment by Premduth** [comment]
test this please

**Comment by Premduth** [comment]
@sabarinaxil do you know what is going on here? Trying to clean up PRs

**Comment by sabarinaxil** [comment]
Pushed Directly

**Comment by sabarinaxil** [comment]
@Premduth , I was testing this to get failure log requested by Subbu. I have closed this PR.

**Pull request closed without merging**
