### PR TITLE
Removed iw-g28m-sm20-3d512m-e008g-bie board file

### PR DESCRIPTION
**Pull request by iwave-768**
Removed iw-g28m-sm20-3d512m-e008g-bie board file from master branch

### CODE REVIEW

**Comment by iwave-768** [comment]
May i know the status ?

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
@iwave-768, our pipeline is flagging an issue with ghost file again as shown below: 
image

**Comment by ADubeyAMD** [comment]
can you please raise a new pull requests with only the files that needs to be checked in. Please do not delete any file once the Pull Request has been made

**Comment by ADubeyAMD** [comment]
@iwave-768, please raise a new Pull request with only the required files for checkin, as mentioned in the message earlier

**Pull request closed without merging**
