### PR TITLE
Add new versions of new and existing Digilent boards to the board store

### PR DESCRIPTION
**Pull request by artvvb**

### CODE REVIEW

**Comment by Premduth** [comment]
ok to test

**Comment by Premduth** [comment]
ok to test

**Comment by Premduth** [comment]
@artvvb please fix the duplicate issues found in new pull request sent:

17:12:58 [06-Mar-2022 17:12:58] {update_catalog.py:354} ERROR - Found multiple enteries for xitem: nexys_video v1.1 owned by digilentinc.com
17:12:58 [06-Mar-2022 17:12:58] {update_catalog.py:355} ERROR - Found @: /scratch/jenkins/xcolinagent06/workspace/Stores_PR_Pipelines/XilinxBoardStore_PR_Pipeline/XilinxBoardStore/boards/Digilent/nexys-video/A.0/xitem.json
17:12:58 [06-Mar-2022 17:12:58] {update_catalog.py:357} ERROR - Found @: /scratch/jenkins/xcolinagent06/workspace/Stores_PR_Pipelines/XilinxBoardStore_PR_Pipeline/XilinxBoardStore/boards/Digilent/nexys_video/A.0/xitem.json
17:12:58 [06-Mar-2022 17:12:58] {update_catalog.py:1611} ERROR - [91mERROR: Found duplicate xitem: nexys_video v1.1 owned by digilentinc.com[0m
17:12:58 Traceback (most recent call last):
17:12:58   File "/proj/rdi/ci/prod/HEAD/sw/continuous/RUNNING_BUILD/regression/src/xhub/scripts/update_catalog.py", line 1601, in main
17:12:58     validateRepo(repo, ValidationPhase.POST)
17:12:58   File "/proj/rdi/ci/prod/HEAD/sw/continuous/RUNNING_BUILD/regression/src/xhub/scripts/update_catalog.py", line 900, in validateRepo
17:12:58     checkDups(repo)
17:12:58   File "/proj/rdi/ci/prod/HEAD/sw/continuous/RUNNING_BUILD/regression/src/xhub/scripts/update_catalog.py", line 358, in checkDups
17:12:58     raise Exception(f'Found duplicate xitem: {xi[0]} v{xi[1]} owned by {xi[2]}')
17:12:58 Exception: Found duplicate xitem: nexys_video v1.1 owned by digilentinc.com
17:12:58 
17:12:58 During handling of the above exception, another exception occurred:
17:12:58

**Comment by artvvb** [comment]
The duplicate issue should now be resolved

**Comment by Premduth** [comment]
ok to test

**Comment by Premduth** [comment]
@artvvb still fails:
12:29:06 [07-Mar-2022 12:29:06] {update_catalog.py:1159} INFO - --------------------------------------------------------------------------------
12:29:06 ['/tools/batonroot/rodin/devkits/lnx64/git-2.12.1/bin/git', 'apply', '--check', '/scratch/jenkins/xcolinagent03/workspace/Stores_PR_Pipelines/XilinxBoardStore_PR_Pipeline/532.patch']
12:29:06 [07-Mar-2022 12:29:06] {update_catalog.py:240} ERROR - [Git] - b'error: boards/Digilent/nexys-video/A.0/board.xml: No such file or directory\nerror: boards/Digilent/nexys-video/A.0/part0_pins.xml: No such file or directory\nerror: boards/Digilent/nexys-video/A.0/preset.xml: No such file or directory\n'
12:29:06 [07-Mar-2022 12:29:06] {update_catalog.py:1608} ERROR - [91mERROR: [GIT] - error: boards/Digilent/nexys-video/A.0/board.xml: No such file or directory
12:29:06 error: boards/Digilent/nexys-video/A.0/part0_pins.xml: No such file or directory
12:29:06 error: boards/Digilent/nexys-video/A.0/preset.xml: No such file or directory

**Comment by artvvb** [comment]
The boards/Digilent/nexys-video folder was removed as it was a duplicate of the file originally in boards/Digilent/nexys_video/A.0, so those files not existing is correct. The correct, updated, files were added in boards/Digilent/nexys_video/1.2.

Did the first test add the unwanted xitem to the catalog and leave it there for the second test, or do I need to ensure that the unwanted xitem does not show up in any of the commits in the PR?

Please advise.

**Comment by Premduth** [comment]
@artvvb we looked at it and the real issue is that these are all in 1 PR..

Here is what needs to be done:
Split the PR into two

    First PR to delete the board files
    Another pull request to add new boards

I will go ahead and close this one, so there is no more confusion.

**Pull request closed without merging**
