### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NaAl-Xlnx**
test PR for Adithya

### CODE REVIEW

**Comment by vsrunga** [comment]
please retest

**Comment by AVXilinx** [comment]
please retest

**Comment by AVXilinx** [comment]
test this please

**Review by sabarinaxil — COMMENTED** [review]
looks good

**Review by sabarinaxil — APPROVED** [review]
I am testing api

**Comment by sabarinaxil** [comment]
Test Completed

**Pull request closed without merging**
