### PR TITLE
Revert "Update for 2019.2 and newer"

### PR DESCRIPTION
**Pull request by NaAl-Xlnx**
This reverts commit 5dc80a1794f38e9b91d3f61ef4d1cbcfb7c03e08.

Please review and merge

### CODE REVIEW

**Review by AVXilinx — APPROVED** [review]

**Comment by AVXilinx** [comment]
ok to test

**Comment by NaAl-Xlnx** [comment]
ok to test

**Comment by NaAl-Xlnx** [comment]
please test this

**Comment by abalasa** [comment]
ok to test

**Pull request merged**
