### PR TITLE
Adding 7CG and 4CG Board Files

### PR DESCRIPTION
**Pull request by iwave-768**

### CODE REVIEW

**Comment by Abhinav2016** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
ok to test

**Review by vsrunga — APPROVED** [review]

**Comment by vsrunga** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
OK to test

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
@iwave-768, the xitem.json is missing with the board files therefore we are unable to merge it to the build. Please add xitem.json to allow the merge

**Comment by iwave-768** [comment]
xitem.json  file is already  added.

image

**Comment by ADubeyAMD** [comment]
@iwave-768 xitem.json for iWave/iw-g30m-c5ev-4e002g-e008g-lia is missing and during the PR merge the script is unable to locate it and thus giving an error. Please update the xitem.json for iw-g30m-c5ev-4e002g-e008g-lia

**Comment by iwave-768** [comment]
i am not able to find this file  (iWave/iw-g30m-c5ev-4e002g-e008g-lia ).  only i uploaded below mentioned files .  please  can you check the name ?
 1.iWave/iw-g30m-c5ev-4e004g-e008g-lia
 2.iWave/iw-g30m-c5ev-4e002g-e008g-bid
image

**Comment by ADubeyAMD** [comment]
@iwave-768 I am closing this pull request as the tool is picking up a filename which is not even present. Please raise a new Pull request and we will try to check if this issues is rectified. If 'iw-g30m-c5ev-4e002g-e008g-lia' is still found then we have to narrow down the location, where the tool is picking up the erronous name

**Comment by ADubeyAMD** [comment]
@iwave-768 Please raise a new Pull request as requested in the message above, thanks

**Pull request closed without merging**
