### PR TITLE
Update Trenz Board Files

### PR DESCRIPTION
**Pull request by JH515**

### CODE REVIEW

**Comment by AVXilinx** [comment]
ok to test

**Comment by Premduth** [comment]
@AVXilinx  can you merge this if you are good with the changes and close the PR?

**Comment by JH515** [comment]
Hi, thanks for merging, but it looks like something was going wrong with your catalog update
https://github.com/Xilinx/XilinxBoardStore/blob/2020.2/catalog/vivado_2020.2.json 
update.
Please check:
 "name": "te0725lp_100", 
this should be removed.  this board file doesn't exist, see:
https://github.com/Xilinx/XilinxBoardStore/tree/2020.2/boards/Trenz_Electronic

br
John

**Comment by JH515** [comment]
I also didn't find TE0725LP_100_2C and TE0725LP_100_2I which should be included in the catalog

I didn't checked other board files until now.


br
John

**Comment by JH515** [comment]
Can it be that you forgot to update the catalog file? From history last update of the catalog file was from November 27, but my merge request was from December

br
John

**Comment by Premduth** [comment]
@vsrunga can you see what is going on here?

**Comment by JH515** [comment]
Hi,
can you tell me why the merge was revered? Problem was on the catalog json file not on the board files. same board files are used for master branch now where catalog json file was correct updated (on master branch it was update by you and  not by contributor). I've done the same procedure like i've done on the on master branch, 20.1 branch and 19.2 branch which was working fine. 

So please let me know how I should procedure to add these board files also to the 20.2 branch.

br
John

**Comment by AVXilinx** [comment]
Hi John,
Yes you are correct. There are no issues with the board files. We have auto merge and catalog update feature turned on in certain branches. 2020.2 was not one of them. But we would like to enable the auto merge and catalog update by default on all branches as that's the approach we want to take going forward. And we would like to ensure that the automated process is robust enough. We are working on enabling it now. Once it’s enabled we will let you know and you can raise the PR again. Sorry for the inconvenience.

Thanks,
Adithya Venkataraman

On Jan 12, 2021, at 1:44 AM, JH515 <notifications@github.com> wrote:

﻿
CAUTION: This message has originated from an External Source. Please use proper judgment and caution when opening attachments, clicking links, or responding to this email.


Hi,
can you tell me why the merge was revered? Problem was on the catalog json file not on the board files. same board files are used for master branch now where catalog json file was correct updated (on master branch it was update by you and not by contributor). I've done the same procedure like i've done on the on master branch, 20.1 branch and 19.2 branch which was working fine.

So please let me know how I should procedure to add these board files also to the 20.2 branch.

br
John

**Comment by JH515** [comment]
Ok, let me know when I can start new PR for 2020.2

br
John

**Pull request merged**
