### PR TITLE
Adding board definition for admpa100_2ms, version 1.0 & admpa101_2ms, version 1.1

### PR DESCRIPTION
**Pull request by twhitlock**

### CODE REVIEW

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
@twhitlock how are you verifying that the board files are compatible with the future Vivado versions since you have merged these to master branch, and this version will be branched out after EA.

**Comment by twhitlock** [comment]
Hi,

I did not understand this myself until recently, so I asked Xilinx support. Specifically, I wanted to know if we should commit to the master branch as well as for specific Vivado release(s), and how we ensure that the board file doesn't break with a new Vivado release. This is not a subject that is covered by the Xilinx Board Store Wiki. My questions are in black and Xilinx's answers are this color.

------------

1) Are we expected add a new board file to the "master" branch as well as branches corresponding to particular Vivado releases (e.g. 2022.2)?

Pull Requests need to be submitted to master branch so that the board files will be visible in upcoming branches like 2023.1.

But for existing branches a separate pull requests are needed in order to view the board in respective Vivado Version board store.



2) If the answer to 1) above is yes, is this because Xilinx will then ensure that the board file is propagated to whatever branches are created for future Vivado releases, such as the upcoming 2023.1?

Yes, that is Correct



3) If the answer to 1) above is yes, then what guarantees (if any) do we have that Xilinx won't break our board file in some future Vivado release due to changes in Vivado or Xilinx IPs? Are we expected to just sort out any issues like that as and when we become aware of them?

I believe that board files have to be validate once by the user every release at their end.

In addition to this,  Xilinx/AMD will be branching 2023.1 BoardStore on Early Access date. The same happens with any new major release. The 'Dot' releases will fall back to major release.

So, board file authors are encouraged to check their existing board files against the new release every time and make necessary changes, if any.



4) If the answer to 2) above is no, then are we expected to add all of our existing board files to the branch corresponding to each new Vivado release, such as the upcoming 2023.1?

That is correct. Adding to Master gets added to newer releases.
------------



So it seems we should add board files to the master branch, but in the event that a board file gets broken by a new Vivado release (e.g. 2023.1), it's not clear to me what the system is for fixing the problem so that customers don't ever see a broken board file.



Should we use Vivado Early Access to do testing before each official Vivado release? I guess we put it through our tests and fix whatever problems show up?

Best regards
Tomas

**Pull request merged**
